src/Entity/Content.php
<?php

namespace App\Entity;

use App\Repository\ContentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ContentRepository::class)
 * @Vich\Uploadable
 */
class Content
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $version;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="contents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="contents")
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $authorAlt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $summary;

    /**
     * @Vich\UploadableField(mapping="content_icon", fileNameProperty="iconName")
     *
     * @var File|null
     */
    private $iconFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $iconName;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTimeInterface|null
     */
    private $updatedIconAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $iconExternal;

    /**
     * @ORM\Column(type="array")
     */
    private $previewNames = [];

    /**
     * @ORM\OneToMany(targetEntity=Artifact::class, mappedBy="content", orphanRemoval=true)
     */
    private $artifacts;

    /**
     * @ORM\Column(type="boolean")
     */
    private $featured;

    /**
     * @ORM\Column(type="boolean")
     */
    private $approved;

    public function __construct()
    {
        $this->created = new \DateTime();
        $this->updated = new \DateTime();
        $this->updatedIconAt = new \DateTime();
        $this->iconExternal = false;
        $this->artifacts = new ArrayCollection();
        $this->approved = false;
        $this->featured = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function getAuthorName(): ?string
    {
        if ($this->authorAlt != null) {
            return $this->authorAlt;
        }
        return $this->author->getUsername();
    }

    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getType(): ?Category
    {
        return $this->type;
    }

    public function setType(?Category $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAuthorAlt(): ?string
    {
        return $this->authorAlt;
    }

    public function setAuthorAlt(?string $authorAlt): self
    {
        $this->authorAlt = $authorAlt;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getIconName(): ?string
    {
        return $this->iconName;
    }

    public function setIconName(?string $iconName): self
    {
        $this->iconName = $iconName;

        return $this;
    }

    public function getIconExternal(): ?bool
    {
        return $this->iconExternal;
    }

    public function setIconExternal(bool $iconExternal): self
    {
        $this->iconExternal = $iconExternal;

        return $this;
    }

    public function getPreviewNames(): ?array
    {
        return $this->previewNames;
    }

    public function setPreviewNames(array $previewNames): self
    {
        $this->previewNames = $previewNames;

        return $this;
    }

    /**
     * @param File|UploadedFile|null $iconFile
     * @return Content
     */
    public function setIconFile($iconFile = null): self
    {
        $this->iconFile = $iconFile;

        if (null !== $iconFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedIconAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getIconFile()
    {
        return $this->iconFile;
    }

    /**
     * @return Collection|Artifact[]
     */
    public function getArtifacts(): Collection
    {
        return $this->artifacts;
    }

    public function addArtifact(Artifact $artifact): self
    {
        if (!$this->artifacts->contains($artifact)) {
            $this->artifacts[] = $artifact;
            $artifact->setContent($this);
        }

        return $this;
    }

    public function removeArtifact(Artifact $artifact): self
    {
        if ($this->artifacts->contains($artifact)) {
            $this->artifacts->removeElement($artifact);
            // set the owning side to null (unless already changed)
            if ($artifact->getContent() === $this) {
                $artifact->setContent(null);
            }
        }

        return $this;
    }

    public function getFeatured(): ?bool
    {
        return $this->featured;
    }

    public function setFeatured(bool $featured): self
    {
        $this->featured = $featured;

        return $this;
    }

    public function getApproved(): ?bool
    {
        return $this->approved;
    }

    public function setApproved(bool $approved): self
    {
        $this->approved = $approved;

        return $this;
    }
}

src/Form/ContentType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Content;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ContentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('version')
            ->add('description')
            ->add('summary')
            ->add('iconFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'download_label' => static function (Content $content) {
                    return $content->getName();
                },
                'download_uri' => true,
                'image_uri' => true,
                'asset_helper' => true,
            ])
            ->add('type', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ])
            ->add('artifacts', CollectionType::class, [
                'entry_type' => ArtifactType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('submit', SubmitType::class, ['label' => 'Publish']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Content::class,
        ]);
    }
}

src/Controller/ApiV1/ContentController.php
<?php

namespace App\Controller\ApiV1;

use App\Entity\Artifact;
use App\Entity\Category;
use App\Entity\Content;
use App\Repository\ContentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Liip\ImagineBundle\Exception\Config\Filter\NotFoundException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ContentController
 * @package App\Controller\ApiV1
 * @route("/api/v1")
 */
class ContentController extends AbstractController
{
    /**
     * @Route("/content/categories.{_format}", defaults={"_format" = "xml"})
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function categories(EntityManagerInterface $em): Response
    {
        $categories = $em->getRepository(Category::class)->findAll();
        return $this->render('api_v1/content/categories.xml.twig', [
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/content/data/{id}", name="app_api_v1_content_get", defaults={"_format" = "xml"})
     * @param Content $content
     * @return Response
     */
    public function getContent(Content $content, EntityManagerInterface $em): Response
    {
        return $this->render('api_v1/content/get.xml.twig', [
            'content' => $content,
        ]);
    }

    /**
     * @Route("/content/download/{id}/{artifact_id}", name="app_api_v1_content_get", defaults={"_format" = "xml"})
     * @ParamConverter("content", options={"id" = "id"})
     * @param Content $content
     * @return Response
     */
    public function downloadContent(Content $content, int $artifact_id, EntityManagerInterface $em): Response
    {
        $artifact = $content->getArtifacts()->get($artifact_id - 1);
        if ($artifact === NULL) {
            throw new NotFoundException();
        }
        return $this->render('api_v1/content/download.xml.twig', [
            'artifact' => $artifact,
        ]);
    }

    /**
     * @Route("/content/data.{_format}", defaults={"_format" = "xml"})
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function list(EntityManagerInterface $em, Request $request): Response
    {
        /** @var ContentRepository $contentRepository */
        $contentRepository = $em->getRepository(Content::class);
        $contentCount = $contentRepository->count([]);

        $page = $request->get('page') ?? 0;
        $pageSize = $request->get('pagesize') ?? 10;
        $pageSize = max(1, min(100, $pageSize));
        $contents = NULL;
        if ($categories = $request->get('categories')) {
            $contents = $contentRepository->findByCategories($categories, $pageSize, $page * $pageSize);
        } else if ($search = $request->get('search')) {
            // TODO implement search in repository
            $contents = $contentRepository->findBy(['name' => $search], [], $pageSize, $page * $pageSize);
        } else {
            $contents = $contentRepository->findBy([], [], $pageSize, $page * $pageSize);
        }
        return $this->render('api_v1/content/list.xml.twig', [
            'contents' => $contents,
            'contentCount' => $contentCount,
            'itemsPerPage' => $pageSize,
        ]);
    }
}

src/Controller/ApiV1/MainController.php
<?php

namespace App\Controller\ApiV1;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/api/v1/provider.xml", name="api_v1_provider", defaults={"_format": "xml"})
     */
    public function index()
    {
        return $this->render('api_v1/main/index.xml.twig');
    }
}

src/Controller/ContentController.php
<?php

namespace App\Controller;

use App\Entity\Content;
use App\Form\ContentType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ContentController extends AbstractController
{

    /**
     * @Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")
     * @Route("/content/add", name="app_content_add")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function add(Request $request, EntityManagerInterface $em): Response
    {
        $content = new Content();
        $content->setAuthor($this->getUser());
        $form = $this->createForm(ContentType::class, $content);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($content->getArtifacts() as $artifact) {
                $artifact->setContent($content);
                $em->persist($artifact);
            }
            $em->persist($content);
            $em->flush();
            return $this->redirectToRoute('app_profile');
        }

        return $this->render('content/add.html.twig', [
            'title' => "Add new content",
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/content/{id}", name="app_content_view")
     * @param Content $content
     * @return Response
     */
    public function view(Content $content): Response
    {
        return $this->render('content/view.html.twig', [
            'content' => $content,
        ]);
    }

    /**
     * @Security("is_granted('IS_AUTHENTICATED_REMEMBERED')")
     * @Route("/content/edit/{id}", name="app_content_edit")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function edit(Content $content, Request $request, EntityManagerInterface $em): Response
    {
        if ($content->getAuthor() != $this->getUser()) {
            throw new UnauthorizedHttpException("You can't edit the content from someone else.");
        }
        $form = $this->createForm(ContentType::class, $content);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($content);
            $em->flush();
            return $this->redirectToRoute('app_profile');
        }

        return $this->render('content/add.html.twig', [
            'title' => "Add new content",
            'form' => $form->createView(),
        ]);
    }
}

templates/api_v1/content/categories.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
    <totalitems>{{ categories | length }}</totalitems>
  </meta>
  <data>
    {% for category in categories %}
      <category>
        <id>{{ category.id }}</id>
        <name>{{ category.name }}</name>
        <display_name>{{ category.name }}</display_name>
        {% if category.xdgType is not null %}
        <xdg_type>{{ category.xdgType }}</xdg_type>
        {% endif %}
        {% if category.parent is not null %}
          <parent_id>{{ category.parent.id }}</parent_id>
        {% endif %}
      </category>
    {% endfor %}
  </data>
</ocs>

templates/api_v1/content/distributions.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
    <totalitems>{{ distributions | length }}</totalitems>
  </meta>
  <data>
    {% for distribution in distributions %}
      <distribution>
        <id>{{ distribution.id }}</id>
        <name>{{ distribution.name }}</name>
      </distribution>
    {% endfor %}
  </data>
</ocs>

templates/api_v1/content/download.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
  </meta>
  <data>
    <content details="download">
      <downloadway>1</downloadway>
      <downloadprice>0</downloadprice>
      <downloadlink>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(artifact) }}</downloadlink>
      <minetype>image/jpeg</minetype>
      <downloadname>{{ artifact.fileName }}</downloadname>
      <downloadsize>{{ artifact.fileSize }}</downloadsize>
      <downloadtags>data##mimetype=image/jpeg</downloadtags>
    </content>
  </data>
</ocs>

templates/api_v1/content/get.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
  </meta>
  <data>
    <content details="full">
      <id>{{ content.id }}</id>
      <name>{{ content.name }}</name>
      <version>{{ content.version }}</version>
      <typeid>{{ content.type.id }}</typeid>
      <typename>{{ content.type.name }}</typename>
      <language></language>
      <personid>{{ content.authorName }}</personid>
      <changed>{{ content.updated | date("Y-m-d\TH:i:s\P") }}</changed>
      <created>{{ content.created | date("Y-m-d\TH:i:s\P") }}</created>
      <downloads>2</downloads>
      <score>67</score>
      <description>{{ content.description }}</description>
      <summary>{{ content.summary }}</summary>
      <changelog></changelog>
      <comments>0</comments>
      <previewpic1>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(content) }}</previewpic1>
      <smallpreviewpic1>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(content) }}</smallpreviewpic1>
      {% for artifact in content.artifacts %}
        <downloadway{{ loop.index }}>{{ loop.index }}</downloadway{{ loop.index }}>
        <downloadprice{{ loop.index }}>0</downloadprice{{ loop.index }}>
        <downloadlink{{ loop.index }}>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(artifact) }}</downloadlink{{ loop.index }}>
        <downloadname{{ loop.index }}>{{ artifact.fileName }}</downloadname{{ loop.index }}>
        <downloadsize{{ loop.index }}>{{ artifact.fileSize }}</downloadsize{{ loop.index }}>
      {% endfor %}
    </content>
  </data>
</ocs>

templates/api_v1/content/licenses.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
    <totalitems>{{ licenses | length }}</totalitems>
  </meta>
  <data>
    {% for license in license %}
      <license>
        <id>{{ license.id }}</id>
        <name>{{ license.name }}</name>
        <link>https://spdx.org/licenses/{{ license.ref }}.html</link>
        <ref>{{ license.ref }}</ref>
      </license>
    {% endfor %}
  </data>
</ocs>

templates/api_v1/content/list.xml.twig
{#
SPDX-FileCopyrightText: (C) 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-LicenseRef: AGPL-3.0
#}
<?xml version="1.0"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message></message>
    <totalitems>{{ contentCount }}</totalitems>
    <itemsperpage>{{ itemsPerPage }}</itemsperpage>
  </meta>
  <data>
    {% for content in contents %}
      <content details="summary">
        <id>{{ content.id }}</id>
        <name>{{ content.name }}</name>
        <version>{{ content.version }}</version>
        <changed>{{ content.updated | date("Y-m-d\TH:i:s\P") }}</changed>
        <created>{{ content.created | date("Y-m-d\TH:i:s\P") }}</created>
        <typeid>{{ content.type.id }}</typeid>
        <typename>{{ content.type.name }}</typename>
        <language></language>
        <personid>{{ content.authorName }}</personid>
        <downloads>5</downloads>
        <score>50</score>
        <comments>0</comments>
        <ghns_excluded>0</ghns_excluded>
        <preview1>{{ app.request.getSchemeAndHttpHost() }}{{ path('app_content_view', {'id': content.id}) }}</preview1>
        <detailpage>{{ app.request.getSchemeAndHttpHost() }}{{ path('app_content_view', {'id': content.id}) }}</detailpage>
        <tags>cc0</tags>
        <previewpic1>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(content) }}</previewpic1>
        <smallpreviewpic1>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(content) }}</smallpreviewpic1>
        {% for artifact in content.artifacts %}
          <downloadway{{ loop.index }}>1</downloadway{{ loop.index }}>
          <downloadprice{{ loop.index }}>0</downloadprice{{ loop.index }}>
          <downloadlink{{ loop.index }}>{{ app.request.getSchemeAndHttpHost() }}{{ vich_uploader_asset(artifact) }}</downloadlink{{ loop.index }}>
          <downloadname{{ loop.index }}>{{ artifact.fileName }}</downloadname{{ loop.index }}>
          <downloadsize{{ loop.index }}>{{ artifact.fileSize }}</downloadsize{{ loop.index }}>
          <downloadtags{{ loop.index }}>data##mimetype=image/jpeg</downloadtags{{ loop.index }}>
        {% endfor %}
      </content>
    {% endfor %}
  </data>
</ocs>