src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping\Index as Index;

/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(
 *     name="category",
 *     indexes={
 *          @Index(name="lft_ix", columns={"lft"}),
 *          @Index(name="rgt_ix", columns={"rgt"}),
 *          @Index(name="lvl_ix", columns={"lvl"})
 *     })
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Gedmo\TreeLeft()
     * @ORM\Column(type="integer")
     */
    private $lft;

    /**
     * @Gedmo\TreeLevel()
     * @ORM\Column(type="integer")
     */
    private $lvl;

    /**
     * @Gedmo\TreeRight()
     * @ORM\Column(type="integer")
     */
    private $rgt;

    /**
     * @Gedmo\TreeRoot()
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(name="tree_root", referencedColumnName="id", onDelete="cascade")
     */
    private $root;

    /**
     * @Gedmo\TreeParent()
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="cascade")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Category", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

    /**
     * @ORM\OneToMany(targetEntity=Content::class, mappedBy="type", orphanRemoval=true)
     */
    private $contents;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $xdgType;

    public function __construct()
    {
        $this->contents = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): self
    {
        if (!$this->contents->contains($content)) {
            $this->contents[] = $content;
            $content->setType($this);
        }

        return $this;
    }

    public function removeContent(Content $content): self
    {
        if ($this->contents->contains($content)) {
            $this->contents->removeElement($content);
            // set the owning side to null (unless already changed)
            if ($content->getType() === $this) {
                $content->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return Category
     */
    public function getParent(): ?Category
    {
        return $this->parent;
    }

    /**
     * @param Category $parent
     */
    public function setParent($parent): void
    {
        $this->parent = $parent;
    }

    /**
     * @return Category
     */
    public function getRoot(): ?Category
    {
        return $this->root;
    }

    public function getXdgType(): ?string
    {
        return $this->xdgType;
    }

    public function setXdgType(string $xdgType): self
    {
        $this->xdgType = $xdgType;

        return $this;
    }

    public function getChildrens()
    {
        return $this->children;
    }
}

src/Controller/ApiV1/MainController.php
<?php

namespace App\Controller\ApiV1;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/api/v1/provider.xml", name="api_v1_provider", defaults={"_format": "xml"})
     */
    public function index()
    {
        return $this->render('api_v1/main/index.xml.twig');
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Content;
use Doctrine\ORM\EntityManagerInterface;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage", defaults={"_locale", "en"})
     * @return Response
     */
    public function index(EntityManagerInterface $em): Response
    {
        /** @var NestedTreeRepository $repository */
        $repository = $em->getRepository(Category::class);

        $categories = $repository->childrenHierarchy(null, true);

        $contentRepository = $em->getRepository(Content::class);
        $featuredContent = $contentRepository->findAll();
        return $this->render('main/index.html.twig', [
            'featuredContent' => $featuredContent,
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/category/{id}", name="app_category")
     * @param Category $category
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function category(Category $category, EntityManagerInterface $em): Response
    {
        /** @var NestedTreeRepository $repository */
        $repository = $em->getRepository(Category::class);
        $categories = $repository->getChildren($category);

        return $this->render('main/category.html.twig', [
            "categories" => $categories,
            "category" => $category,
        ]);
    }
}

templates/main/category.html.twig
{#
SPDX-FileCopyrightText: 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-License-Identifier: AGPL-3.0-or-later
#}
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}
{% block description %}The homepage of this website{% endblock %}
{% block image %}{% endblock %}
{% block canonical %}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-3">
      {% for category in category.childrens %}
        <a href="{{ path('app_category', {'id': category.id}) }}">{{ category.name }}</a>
      {% endfor %}
    </div>
    <div class="col-9">
      <h1 class="h4">{{ category.name }}</h1>
    </div>
  </div>
{% endblock %}

templates/main/index.html.twig
{#
SPDX-FileCopyrightText: 2020 Carl Schwan <carl@carlschwan.eu>

SPDX-License-Identifier: AGPL-3.0-or-later
#}
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}
{% block description %}The homepage of this website{% endblock %}
{% block image %}{% endblock %}
{% block canonical %}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-3">
      {% for category in categories %}
        <a href="{{ path('app_category', {'id': category.id}) }}">{{ category.name }}</a>
      {% endfor %}
    </div>
  </div>
  <main class="container">
    <h2 class="h3">Featured</h2>
    <div class="row">
      {% for content in featuredContent %}
        <div class="col-3 d-flex">
          <img src="{{ vich_uploader_asset(content) }}" class="img-fluid" />
          <div>
            <a class="h4" href="#">{{ content.name }}</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </main>
{% endblock %}